language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

matrix:
    fast_finish: true
    include:
        - php: 8.0
          env: LARAVEL_VERSION=~8.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0
        - php: 8.0
          env: LARAVEL_VERSION=~9.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0
        - php: 8.1
          env: LARAVEL_VERSION=~8.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0
        - php: 8.1
          env: LARAVEL_VERSION=~9.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0

before_install:
    - travis_retry composer self-update

install:
    - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --no-interaction --prefer-dist
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --no-interaction --prefer-dist
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --no-interaction --prefer-dist
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

branches:
    only:
        - master

notifications:
    email: false
